### PR TITLE
New projects page

### PR DESCRIPTION
**Pull request by bianca2511**

### CODE REVIEW

**Comment by DusterTheFirst** [comment]
@bianca2511 It is also worth going over the sponsors page to fix the formatting of the images and text

**Comment by DusterTheFirst** [comment]
https://decapcms.org/docs/widgets/?# "Variable Type Widgets"

**Comment by bianca2511** [comment]
@DusterTheFirst put the stats through decap please <3

**Comment by DusterTheFirst** [comment]
@bianca2511 look at the footer, it may need a max-width. On wide screens it looks a bit goofy.

**Comment by DusterTheFirst** [comment]
> @DusterTheFirst put the stats through decap please <3

Done

**Comment by DusterTheFirst** [comment]
After the 25th, I will merge this with the projects page disabled.

**Review by DusterTheFirst — APPROVED** [review]

**Pull request merged**
